We will start by testing the search functionality. Previously, while creating the Service, grails also created the `ClassroomServiceSpec`. Navigate to the file and clean it up so it resembles this:

[source, groovy]
.src/test/groovy/grails/mock/basics/ClassroomServiceSpec.groovy
----
package grails.mock.basics

import grails.test.mixin.Mock
import grails.test.mixin.TestFor
import spock.lang.Specification

@TestFor(ClassroomService)
class ClassroomServiceSpec extends Specification {

}
----

We will create Domain objects that will be stored in the in-memory implementation of GORM. This enables us interact with the GORM API on a simulated database during a unit test, similar to what would occur on a real database. We will use the @Mock annonation.

Add the @Mock annotation to the top of the Class.

[source, groovy]
----
@Mock([Student, Classroom])
----

Implement a method that will save `Students`. Implement a test that will mock `Students`, run the service method, and then verify the correct result was found.
[source,groovy]
----
include::{sourceDir}/src/test/groovy/grails/mock/basics/ClassroomServiceSpec.groovy[tags=studentsInfo;testFind;mockStudentsOnly]
----

Execute the test command to view the test results.

[source,groovy]
----
grails test-app
----

<1> Data used to populate `Students`.
<2> Save `Students` using the GORM API.
<3> Execution of method will find the objects stored in the in-memory GORM database.

